# Generated by Django 5.2.2 on 2025-06-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_videoprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprogress',
            old_name='last_time',
            new_name='progress',
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together=set(),
        ),
    ]
