# Generated by Django 5.2.2 on 2025-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_created',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_images/default.jpg', upload_to='course_images/'),
        ),
    ]
