# Generated by Django 5.2.2 on 2025-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_students_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
